Fix clippy warnings
dmerejkowsky/minigrep pull request #1
Opened 2022-07-09 20:10 UTC by micwoj92

2022-07-11 19:03 UTC, dmerejkowsky requested changes

2022-07-11 19:03 UTC, dmerejkowsky commented on src/lib.rs
> +        let case_sensitive = env::var("MINIGREP_CASE_INSENSITIVE").is_err();
that's a good example of a bad clippy fix ;) I find the code is less clear this way

2022-07-12 00:02 UTC, micwoj92 commented on src/lib.rs
> +        let case_sensitive = env::var("MINIGREP_CASE_INSENSITIVE").is_err();
Reverted that

2022-07-13 09:01 UTC, dmerejkowsky commented
Ok then ;) Thanks for the patch.

2022-07-13 09:01 UTC, merged